# Generated by Django 2.2.6 on 2019-10-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TwoGive', '0003_auto_20191028_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TwoGive.authUser'),
        ),
    ]
