# Generated by Django 2.2.6 on 2019-11-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoGive', '0005_auto_20191030_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='product-img/pro-big-1.jpg', upload_to='product-img/'),
        ),
    ]
