# Generated by Django 2.2.6 on 2019-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoGive', '0009_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
