# Generated by Django 2.2.6 on 2019-11-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwoGive', '0011_cart_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='product',
            new_name='item',
        ),
    ]
