# Generated by Django 2.2.6 on 2019-11-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwoGive', '0012_auto_20191103_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
